# Generated by Django 3.0.5 on 2020-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cover_Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Artist', models.CharField(blank=True, max_length=300, null=True)),
                ('Title', models.CharField(blank=True, max_length=300, null=True)),
                ('Label', models.CharField(blank=True, max_length=300, null=True)),
                ('Year', models.CharField(blank=True, max_length=4, null=True)),
                ('Catalogue_Number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
