# Generated by Django 3.0.5 on 2020-04-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_auto_20200409_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
